### ISSUE TITLE
Deprecate in favor of express-graphql

### ISSUE THREAD

**Issue by timneutkens** [ConnerPetzold/micro-graphql#1]
Maybe this repo should be deprecated since you can just pass in express-graphql to handle the request (with support for graphiql). I made a little repo explaining how to do it: https://github.com/timneutkens/micro-graphql

**Comment by ConnerPetzold** [comment]
Ah yeah I suppose that would be best -- what's the story for per-request configuration?

**Comment by timneutkens** [comment]
Sending this from my phone. But it's something like this: 'module.exports = (req, res) => {graphql(config)(req,res)}
